### ISSUE TITLE
tab-safe?

### ISSUE THREAD

**Issue by dereuromark** [World-Architects/cakephp-query-param-preserver#1]
Isnt the only real good solution to not use session and always pass query strings along with each URL?
Doesn't this plugin currently lack tab-safe query string handling?

Buggy scenario:
2 tabs open, in one you browse somewhere else (filtering, sorting, page xyz, ...), then you click on page 2 in the first one and suddendly everything is totally messed up etc or you get a 404 not found page.

**Comment by burzum** [comment]
This solution is good enough for us right now. Also if you pass the whole query with *every single URL* on the page the URLs are going to look fugly and become damn long. This not an option either for us.

**Comment by dereuromark** [comment]
The problem I am seeing (and have been experiencing in the past with this approach) is when you have two tabs and they infect each other, and you are on a page 4, and the other sessions result only returns page 2, you suddenly run into a 404 error on this tab, where as you just wanted to go back to 3 here (showing the filters of this current tab).

I don't know, but for me this seems like a hacky workaround with more use cases broken than necessary.
But sure, if usability is not the priority this could be "good enough" I guess.

**Comment by burzum** [comment]
> The problem I am seeing (and have been experiencing in the past with this approach) is when you have two tabs and they infect each other, and you are on a page 4, and the other tab sessions result only returns page 2, you suddenly run into a 404 error on this tab, where as you just wanted to go back to 3 here (showing the filters of this current tab).

I'm aware of that, but this should not happen the way this is implemented. I haven't tried it honestly. It should not happen. Because if you're on tab 2 and page 4 and click on next (page 5) it will merge the params but prioritize the current params. https://github.com/World-Architects/cakephp-query-param-preserver/blob/master/src/Controller/Component/QueryParamPreserverComponent.php#L73

Would you mind to try it or provide a test? :)

> One idea could be to internally store them as hash key 

This is already done, see https://github.com/World-Architects/cakephp-query-param-preserver/blob/master/src/Controller/Component/QueryParamPreserverComponent.php#L58
